image: jelaniwoods/appdev2021-vanilla-rails@sha256:201e1921284a5bc3391176641dedacc4673dad4e37250e4170a4d1e0edc14ce2

tasks:
  - init: yarn install --check-files && bin/setup 
ports:
  - port: 3000
    onOpen: open-preview
    
vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced@0.5.1:s3vD5qiY6/HbtRrgDlbMiQ==
    - vortizhe.simple-ruby-erb@0.2.1:BzpDuNAqJwUkxqT2t1YIuQ==
    - CraigMaslowski.erb@0.0.1:5znDha/nn0PphUrpB9a5Nw==
    - Vense.rails-snippets@0.5.0:w1Rd4bmOp7tM7xc3UJruRQ==
    - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
